# TODO: Use consistent naming for keys
shared:
  code: &code
    - kitty
    - org.kde.konsole
    - Alacritty
    - code
  terminal: &terminal
    - kitty
    - org.kde.konsole
    - Alacritty
  alone_timeout_millis: &alone_timeout_millis 200
  windows_devices: &windows_devices
    - ITE Tech. Inc. ITE Device(8910) Keyboard

modmap:
  - name: Control
    remap:
      CapsLock:
        held: Control_L
        alone: Esc
        alone_timeout_millis: *alone_timeout_millis
      Semicolon:
        held: Control_R
        alone: Semicolon
        alone_timeout_millis: *alone_timeout_millis
      Esc: CapsLock

  - name: Windows
    device:
      only: *windows_devices
    remap:
      WIN_L: ALT_L
      ALT_L: WIN_L
      ALT_R: WIN_R
      CTRL_R: ALT_R

keymap:
  - name: Non-code applications
    application:
      not: *code
    exact_match: true
    remap:
      C-p: up
      C-n: down
      C-w: C-backspace
      C-h: backspace
      C-u: [Shift-Home, Backspace]
      C-k: [Shift-End, Backspace]
      C-m: enter
      C-f: right
      C-b: left
      C-c: Super-c
      C-v: Super-v
      C-x: Super-x
      C-a: Home
      c-e: End
      C-s: Super-s
      C-t: Super-t
      C-z: Super-z
      C-equal: Super-equal
      C-minus: Super-minus
      C-Shift-z: Super-Shift-z
      M-f: C-right
      M-b: C-left
      # map the originals to super
      Super-p: C-p
      Super-n: C-n
      Super-w: C-w
      Super-h: C-h
      Super-u: C-u
      Super-m: C-m
      Super-f: C-f
      Super-b: C-b
      Super-c: C-c
      Super-v: C-v
      Super-x: C-x
      Super-a: C-a
      Super-s: C-s
      Super-t: C-t
      Super-z: C-z
      Super-equal: C-equal
      Super-minus: C-minus
      Super-Shift-z: C-Shift-z

  - name: Terminal applications
    application:
      only: *terminal
    exact_match: true
    remap:
      Super-c: C-Shift-c
      Super-v: C-Shift-v
