alias batman='bat --language=man --style=plain --paging=always'
alias bb='brew bundle install --global'
alias dab='databricks bundle'
alias ghmp='gh markdown-preview --markdown-mode'
alias icat='kitten icat'
alias lzd='lazydocker'
alias lzg='lazygit'
alias opc='opencode'
alias pydoc='python3 -m pydoc'
alias ur='uv run'
alias v='nvim'
alias view='nvim -R'
alias yless="jless --yaml"

alias l='eza --color=auto --icons=auto'
alias la='eza --long --all --color=auto --icons=auto --git'
alias ll='eza --long --color=auto --icons=auto --git'
alias tree='eza --tree --color=auto --icons=auto --git-ignore'

alias -g ......='../../../../..'
alias -g .....='../../../..'
alias -g ....='../../..'
alias -g ...='../..'
