# HACK: if brew self updates then it fails to discover the Brewfile, so we run it again
alias bb='brew bundle --global || brew bundle --global'

alias v='nvim'
alias docker='podman'
alias cd='z'
alias ls='eza --color=auto --icons=auto'
alias tree='eza --tree --color=auto --icons=auto'
alias ll='eza --long --color=auto --icons=auto --git'
alias la='eza --long --all --color=auto --icons=auto --git'
alias lzg='lazygit'
alias lzd='lazydocker'
alias batman='bat --language=man --style=plain --paging=always'
alias pip='uv pip'
alias pipx='uv tool'
alias icat='kitten icat'
alias dab='databricks bundle'
alias -g ...='../..'
alias -g ....='../../..'
alias -g .....='../../../..'
alias -g ......='../../../../..'
