# import = ["~/.config/alacritty/alacritty-theme/themes/catppuccin_mocha.toml"]
import = ["~/.config/alacritty/alacritty-theme/themes/gruvbox_dark.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[window]
option_as_alt = "Both"

[font]
normal.family = "JetbrainsMonoNL Nerd Font"
normal.style = "Regular"
size = 13.0

[mouse]
hide_when_typing = true
