import = ["~/.config/alacritty/alacritty-theme/themes/catppuccin_mocha.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[window]
option_as_alt = "Both"

[font]
normal.family = "JetbrainsMonoNL Nerd Font"
normal.style = "Regular"
size = 13.0
offset.x = 0
offset.y = 6

[mouse]
hide_when_typing = true
