import = ["~/.config/alacritty/catppuccin-alacritty/catppuccin-mocha.toml"]
# import = ["~/.config/alacritty/alacritty-theme/themes/gruvbox_dark.toml"]

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux new-session -A"]

# [env]
# LC_ALL = "C.UTF-8"

[colors]
draw_bold_text_with_bright_colors = true

[window]
option_as_alt = "Both"

[font]
normal.family = "JetbrainsMonoNL Nerd Font"
normal.style = "Regular"
size = 15.0

[mouse]
hide_when_typing = true
