[general]
# import = ["./catppuccin-alacritty/catppuccin-macchiato.toml"]
# import = ["./gruvbox_material_medium_dark_patched.toml"]
import = ["alacritty-theme/themes/kanagawa_wave.toml"]

[terminal.shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux new-session -A"]

[colors]
draw_bold_text_with_bright_colors = true

[window]
option_as_alt = "Both"

[font]
normal.family = "JetbrainsMonoNL Nerd Font"
normal.style = "Regular"
size = 11.0

[mouse]
hide_when_typing = true
