import = ["~/.config/alacritty/alacritty-theme/themes/catppuccin_frappe.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[window]
option_as_alt = "Both"

[font]
normal.family = "JetbrainsMonoNL Nerd Font"
size = 13.0
offset.x = 1
offset.y = 5

[mouse]
hide_when_typing = true
