[general]
import = ["./catppuccin-alacritty/catppuccin-macchiato.toml"]
# import = ["./alacritty-theme/themes/gruvbox_dark.toml"]

[terminal.shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux new-session -A"]

[env]
LC_CTYPE = "el_GR.UTF-8"

[colors]
draw_bold_text_with_bright_colors = true

[window]
option_as_alt = "Both"

[font]
normal.family = "JetbrainsMonoNL Nerd Font"
normal.style = "Regular"
size = 13.0

[mouse]
hide_when_typing = true
